### ISSUE TITLE
Navigation Bar - #1

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
- [x] setup webpack, include Bootstrap and Fontawesome
- [x] create `src` folder, add `javascripts` folder >`main.js`
- [x] inside `src` > `javascripts` > `components` folder 
- [x] inside `src` > `styles` folder > `main.scss`
- [x] hard-code navbar into `index.html`. use Bootstrap navbar
``` html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="input-text" id="message-input" placeholder="New Message" aria-label="Enter New Message">
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit" id="message-submit-btn">Enter</button>
     <button class="btn btn-outline-dark my-2 my-sm-0" type="submit" id="clear-message-btn">Clear</button>
    </form>
  </div>
</nav>
```

- [x] fontAwesome icon for logo:
`<i class="fab fa-pagelines"></i>`

- [x] position fixed to top
`<div class="fixed-top">navbar code goes here</div>`
![image](https://user-images.githubusercontent.com/52139891/76272032-34ba1880-6248-11ea-8d65-8bca2953c43b.png)

**Comment by christopherjohnson1** [comment]
![chatty-navbar](https://user-images.githubusercontent.com/58916138/76433380-3d166e80-6382-11ea-947d-15a33842982a.png)
