### ISSUE TITLE
Clear Messages - #7

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#14]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
Function to clear history:
- [x] create a new file in `src/javascripts/components` called `clearMessages.js`
- [x] inside the file, create a new function called clearAllMessages and import `messageData.js`
- [x] this function should access the array of messages in `messageData.js` and use setter function to set the array to be empty
- [x] then, this function should use jquery to add `class="disabled"` to the Clear button
- [x] finally, call the `displayAllMessages` function from `displayMessages.js` so that the emptied array re-prints
- [x] edit the code for message Enter button to re-enable the Clear button when clicked ([jQuery remove class](https://api.jquery.com/removeClass/)) (so when a new message is added, user can now clear again)

**Comment by spookycutie08** [comment]
Let us know if you need help with adding classes using jquery.

**Comment by spookycutie08** [comment]
#### Things I did that were not listed, but needed:
* didn't _specifically_ say to import `displayMessages.js`
* had to edit our original Setter function (also plays into tickets earlier than this one) and create another one that Sets the _array_, not just a single message

No big deal, just what it's worth if we look at these tickets again... :)
