### ISSUE TITLE
Large Text - #11

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
- [ ] add a Bootstrap checkbox into the navbar code, to appear under the input field:
```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="large-text-checkbox">
  <label class="form-check-label" for="defaultCheck1">
    Large Text
  </label>
</div>
```
- [ ] create a function called `largeTextToggle` that uses jquery to give class of `large-text` to the <body> tag when the box is checked:
```js
$('#large-text-checkbox').checked{
  $("body").toggleClass("large-text");
};
```
- [ ] import and call `largeTextToggle` in the `main.js` function `init`
- [ ] create the class in `main.scss` and give it a large text size

**Comment by spookycutie08** [comment]
[jQuery toggle documentation](https://www.w3schools.com/jquery/html_toggleclass.asp)

if this doesn't work, may have to use 'click' event listener as backup...
