### ISSUE TITLE
Delete Message - #8

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#16]
## User Story
As a user I should be able to delete messages my messages.

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
- [x] inside `src/javascripts/components` create a new file called `deleteMessage.js`
- [x] import `messageData.js` and `userData.js`
- [x] edit the `displayAllMessages` function to include a button on each message (to use for delete)
bootstrap button
- [x] that button should use template literal to be assigned an `id` which is the `messageId`
- [x] when button is clicked, it should call a function `deleteMessage`

This function should:
- [x] use `.find` method on the `messages` array and find the individual message which has a `messageId` that matches the button id,
- [x] then remove that message object from the array,
- [x] then call `displayAllMessages` again so that the screen updates

** NOTE** if this creates a dependency issue between modules, consider using a printButtons function separately, instead of modifying the `displayAllMessages`. See code snippet in comment below.

**Comment by spookycutie08** [comment]
for reference:
``` js
printButtons = (divId) => {
    let domString = '';
    domString += '<div class="row">';
    domString += `<div class="col-6"><button class="col-12 btn btn-outline-success feed-button ${divId === 'graveyard' ? 'disabled' : ''}"><i class="fas fa-drumstick-bite"></i></button></div>`;
    domString += `<div class="col-6"><button class="col-12 btn btn-outline-warning adv-button ${divId === 'graveyard' ? 'disabled' : ''}"><i class="fas fa-hiking"></i></button></div>`;
    domString += '</div>';
    domString += '<div class="row">';
    domString += `<div class="col-6"><button class="col-12 btn btn-outline-dark single-dino"><i class="far fa-eye"></i></button></div>`;
    domString += `<div class="col-6"><button class="col-12 btn btn-outline-danger delete-dino ${divId === 'graveyard' ? 'disabled' : ''}"><i class="far fa-trash-alt"></i></button></div>`;
    domString += '</div>';
    return domString;
}
```
