### ISSUE TITLE
Display Message - #3

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `helpers/data/messageData.js`
**And** when they add messages it should add them to the list

## Dev Notes
- [x] create `utils.js` file in `src/javascripts/helpers` folder and create the `printToDom` function inside, then export
- [x] create new file `displayMessages.js` in `src/javascripts/components/` then:
- [x] import `messageData.js`
- [x] Use a bootstrap list group and use the .forEach method to loop through the messages array to display them on the page. 
Bootstrap list group:
```
<ul class="list-group">
  <li class="list-group-item">each message text</li>
</ul>
```
- [x] create a new function called `displayAllMessages` that uses `.forEach` to loop through all messages in `messageData.js` and create a new list item `<li>` for each message, then print all to page with `printToDom`
- [x] export default `displayAllMessages`
- [x] in `main.js`, import `displayAllMessages` and create an `init` function that calls `displayAllMessages` on page load

**Comment by spookycutie08** [comment]
```js
import houseData from '../../helpers/data/houseData';import utils from '../../helpers/utils';
import studentCard from '../studentCard/studentCard';
import './studentList.scss';
const createStudentList = (students) => {  const houses = houseData.getHouses();  let domString = '<ul class="student-list">';  students.forEach((student) => {    const studentHouse = houses.find((x) => x.id === student.houseId);    domString += studentCard.createStudentCard(student, studentHouse);  });  domString += '</ul>';  utils.printToDom('student-container', domString);};
export default { createStudentList };
```

**Comment by spookycutie08** [comment]
#### Things I did that were not listed, but needed:
* add `<div>` container into `index.html`
* didn't _specifically_ say to import `utils.js`

No big deal, just what it's worth if we look at these tickets again... :)
