### ISSUE TITLE
Seed Data - #2

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#3]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `helpers/data/messageData.js`
**And** this file should have seed data for 5 messages

## Dev Notes
- [x] create `helpers` folder inside `javascripts`
- [x] inside that, create `data` folder
- [x] inside that, create `messageData.js` file
- [x] in that file, create an array of messages called `messages` with five objects
- [x] each message object should have two sentences of **cupcake ipsum** text
- [x] each message object should have a user id between 1 and 5, and a unique message id - see Kayla's data comment below
** Assume this data is for page-load only and does not interact with userData.js YET
- [x] create `getter` and `setter` functions and export them

**Comment by wickedanna** [comment]
I went ahead and wrote the data for this ticket:
```
const messages = [
{ 
userId: 'user1', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'abcedfg'
},
{ 
userId: 'user2', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'hijklmo'
},
{ 
userId: 'user3', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'pqrst'
},
{ 
userId: 'user4', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'uvwxyz'
},
{ 
userId: 'user5', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'auyerh'
},
];
```

**Comment by spookycutie08** [comment]
I edited Kayla's data, just to put ' ' around the user id's, since they need to be strings that match the userData. :)

**Comment by wickedanna** [comment]
Thanks! I actually just came back to this ticket to correct that.
