### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#5]
## USER STORY
As a user, I want to be able to select custom colors for the page theme

## AC (Zoe's text for ticket)
1. Add a button/link to the UI labeled "Change Theme".
1. Remove the existing elements for changing the theme.
1. When user click on Change Theme element, show a Bootstrap modal dialog box.
1. Inside the modal, show two color picker fields - one for background color and one for font color.
1. Add a *Save* and *Cancel* button to modal.
1. When user clicks *Save* apply the chosen colors.

## DEV NOTES
- [x] remove the Dark Theme checkbox in the navbar
- [x] replace it with a button called Change Theme
- [x] in `index.html`, hard-code a button labeled "Change Theme".  Give it an id "change-theme-btn"
- [x] create a new component in `src/javascripts` folder called `changeTheme.js`
- [x] in `main.js`, create jQuery event listener inside the `init` function body - should listen for click on the id "change-theme-btn" and run function `changeTheme`
- [x] in `changeTheme.js`, build the function `changeTheme` that will:
- [x] use jQuery to `.addClassList` to the `body` tag of html.  Something like:
```document.querySelector('body').classList.toggle('black');```
but class name will be 'theme'
- [ ] create a new file called `_variables.scss`, and populate it with a `@mixin` 
- [ ] the mixin should take in two arguments: `background` and `text`
- [ ] build the mixin function to take these arguments and apply them as background-color and text-color.
- [ ] in `main.scss` , import `_variables.scss`.  Create a ruleset for 'theme' class that contains the `@include` for that mixin you just built
``` scss
@mixin change-theme ($background, $text) {
  background-color: $background;
  text-color: $text;
}
```
- [ ] in `changeTheme.js`, create a new function called `viewThemeModal`, that builds a domString of what should be built into the modal:
* container div
* some text that labels the sections for background and text color ("Select Background:")
* two sets of radio buttons (for background and text colors)
* each set should have three colors to choose from (you pick!)
* two buttons - Save and Cancel
* Save needs an id `save-theme-btn`
* Cancel needs an id `cancel-theme-btn`
* modal code at the bottom(see links)
[link to Bootstrap Modal](https://getbootstrap.com/docs/4.4/components/modal/)
see lines 58-61(close) and 81-84(open)  of 
[Bethany's BearWatcher project](https://github.com/bwhitworth/bear-watcher/blob/master/javascripts/components/river.js)
see lines 204-207 and 152-155 of
[Zoe's Dino Kennel project](https://github.com/nss-evening-cohort-11/dino-kennel/blob/master/main.js)
- [x] create a short function that closes the modal (see line 58-61 of Bethany's bearwatcher).  Add jQuery event listener to the Cancel button to call that function and close the modal.
- [ ] reference Kayla's use of radio buttons for the users to find the value of the radio buttons for color.  
``` js
const getRadioVal = () => {
  let val;
  Array.from($('.user-radio-btns')).forEach((item) => {
    if (item.checked) {
      val = item.id;
    }
  });
  return val;
};
```
- [ ] when Save button is clicked, runs a function:
* jQuery that .addClass(run getRadioVal to return the value of radio button) to the body
[hogwarts reference](https://github.com/nss-evening-cohort-11/hogwarts/blob/master/src/javascripts/components/studentCard/studentCard.scss)

* reference Dark Theme ticket for how-to
- [ ] eventually remove the .scss code for Dark Theme

**Comment by spookycutie08** [comment]
Done, but a lot different than how we expected it to go with this ticket...
