### ISSUE TITLE
Multiple Users - #5

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#6]
## User Story
As a user, when on the page I should be able to send messages from my user.

## AC
**WHEN** the page loads
**THEN** I should see some way to select my user
**AND** when I add messages my user should get credit

## Dev Notes:
- [x] Create a helpers/data/userData.js file that holds an array of users (*see example below*).
```js
const users = [
  { id: 'user1', name: 'Xavier' },
  { id: 'user2', name: 'Joanna' },
  { id: 'user3', name: 'Gunter' },
  { id: 'user4', name: 'Sven' },
  { id: 'user5', name: 'Mackenzie' }
];
```
- [x] create `getter` and `setter` functions and export them
- [x] Next to the message input box, there should be a radio button group for each name in the list (edit the Navbar hardcode in `index.html` to include these)
Here is one radio button from Bootstrap:
``` html
<div class="custom-control custom-radio">
  <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
  <label class="custom-control-label" for="customRadio1">Toggle this custom radio</label>
</div>
```
- [x] When a user enters a message, it should be prepended with the chosen user's name, in bold text. (edit the `addNewMessage` function. Use the value of the active radio button to include this user's `id` to the message object that gets pushed into messageData.js array)
![image](https://user-images.githubusercontent.com/52139891/76272001-1fdd8500-6248-11ea-8439-1fa41674cf8d.png)

**Comment by spookycutie08** [comment]
```js
import houseData from '../../helpers/data/houseData';import utils from '../../helpers/utils';
import studentCard from '../studentCard/studentCard';
import './studentList.scss';
const createStudentList = (students) => {  const houses = houseData.getHouses();  let domString = '<ul class="student-list">';  students.forEach((student) => {    const studentHouse = houses.find((x) => x.id === student.houseId);    domString += studentCard.createStudentCard(student, studentHouse);  });  domString += '</ul>';  utils.printToDom('student-container', domString);};
export default { createStudentList };
```
