### ISSUE TITLE
Timestamps - #10

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#8]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
- [x] do the thing ^
- [x] in `messageData.js`, give the seed data objects some fictional timestamps.  This will be a new key value pair called `stamp`
```js
const messages = [
{ 
userId: 'user1', 
message: ‘Toffee tootsie roll toffee cake cookie brownie. Tootsie roll soufflé wafer chocolate powder candy icing’,
messageId: 'abcedfg',
stamp: 'September 8, 2014 8:02 PM'
},
```
- [x] edit the `addNewMessage` function in `newMessage.js` to also push in a key value of `stamp` with each message, and the value will be `moment().format('MMMM Do YYYY, h:mm A')`
- [x] edit the `displayAllMessages` function to include the stamp as part of the `domString` (at the end, after the message)

**Comment by christopherjohnson1** [comment]
![image](https://user-images.githubusercontent.com/58916138/76674217-d4dead00-657a-11ea-8bda-ead2e7d1ab52.png)
